config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :teams
  root to: 'welcome#index'
  resource :prediction, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ('/')
  # root 'posts#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  append_view_path(Dir.glob(Rails.root.join('app/packages/*/views')))
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/views/games/_game.html.slim
div id="#{dom_id game}"
  p
    strong Date:
    =< game.date
  p
    strong Location:
    =< game.location
  p
    strong First team:
    =< game.first_team_id
  p
    strong Second team:
    =< game.second_team_id
  p
    strong Winning team:
    =< game.winning_team
  p
    strong First team score:
    =< game.first_team_score
  p
    strong Second team score:
    =< game.second_team_score

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sportsball" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
|<!DOCTYPE html>
html
  head
    title Sportsball App

    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbolinks-track": "reload"
    = javascript_importmap_tags

  header
    .top-bar
      .top-bar-left
        ul.menu
          li
            = link_to root_path do
              = image_tag "logo.png", width: "15px"
              | Sportsball
          li =link_to "Teams", teams_path
          li =link_to "Games", games_path
          li =link_to "Predictions", new_prediction_path

  main
    .row
      .small-12.columns
        = yield

  javascript:
    $(document).foundation();